### ISSUE TITLE
Bug: Incorrect logging in GtmSupport.trackView()

### ISSUE THREAD

**Issue by siegert-dit** [gtm-support/core#50] opened 2021-07-28 09:13 UTC
Regarding method `trackView`: https://github.com/gtm-support/core/blob/a5024c31024789bbdaeeb842bf2e9a1fc311e203/src/gtm-support.ts#L152-L166

Summary: When the plugin is initialized as disabled but with debugging enabled, `trackView()` logs an event to console even though it shouldn’t.

Steps to reproduce:
1. Set `this.options.debug` to true
2. Set `this.options.enabled` to false
3. Call `trackView`

Expected:
Log message `[GTM-Support]: Dispatching TrackView …` is _not_ present in the console

Actual:
Log message `[GTM-Support]: Dispatching TrackView …` is present in the console

The reason why I think this is a bug: The log message made me believe our setup is incorrect because the plugin (even though configured as disabled) claimed it tracked views but nothing turned up in the dataLayer array. Took some time to figure out what actually was happening. The plugin should only log when it actually pushes something to the dataLayer array.

## Info

| Tool    | Version       |
| ------- | ------------- |
| Package | v1.1.0        |
| Node    | v12.22.1        |
| OS      | mac |

**Comment by Shinigami92** [comment] 2021-07-30 09:11
Uhm... 

https://github.com/gtm-support/core/blob/a5024c31024789bbdaeeb842bf2e9a1fc311e203/src/gtm-support.ts#L145-L146

I think I did this by design...
So maybe we should add documentation in additional places, or I could logout something like that the plugin is in disabled state 🤔 

What do you think?

**Comment by Shinigami92** [comment] 2021-09-18 20:52
closed via https://github.com/gtm-support/core/commit/33ed2424c61665129e2bf3d3daf0d708ef5b9050

**Closed by Shinigami92** 2021-09-18 20:52 UTC
